version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: DockerfilePepe
    ports:
      - "9300:8000"
    restart: always
  
  db:
    image: mipostgres:latest
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: miapp
    ports:
      - "5432:5432"
    restart: always
